### ISSUE TITLE
Code style - normalize yaml task files

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#11]
Let's normalize our ansible tasks, i.e. change [this](https://github.com/liquidinvestigations/setup/blob/9cf7993/ansible/roles/common/tasks/main.yml#L77-L79):
```yaml
- name: nginx default site conf
  template: src=nginx/default
            dest=/etc/nginx/sites-enabled/default
```

to this:
```yaml
- name: nginx default site conf
  template:
    src: nginx/default
    dest: /etc/nginx/sites-enabled/default
```
